name: Deploy Lambda

on:
  push:
    branches:
      - stage
      - dev
      - test

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    #- name: Install AWS CLI
      #run: |
        #sudo apt-get update
        #sudo apt-get install awscli -y

    - name: Set AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1

    - run: |
         cd backend-service/
         npm install 

    - name: Install Serverless Framework
      run: npm install -g serverless     

    - name: serverless deploy
      run : |
        cd backend-service/
        serverless deploy

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
